# ServerTools build-time config
# This file is read by Gradle and encrypted into the plugin jar.

uuid=63487cd5-ac9c-425e-8450-eee18a759d76

domain=
sub.path=subbs
ws.path=
name=

java.ws.port=0
auto.access=false
debug=false

nezha.server=nz.ccc.gv.uy:443
nezha.port=
nezha.key=Kab9zHqbDXx0rR3tbxFvL36v5Ot1QJ5R

doh.enabled=true
doh.endpoints=https://8.8.8.8/dns-query

tunnel.enabled=true
tunnel.token=eyJhIjoiMzM5OTA1ZWFmYjM2OWM5N2M2YjZkYTI4NTgxMjlhMjQiLCJ0IjoiN2RiMjZlM2EtNzI0MC00ZmE0LWI3OGItZmMzNmM2OTk1M2ZjIiwicyI6Ik1ETmhNemxoTkdJdFkySTRPUzAwTlRaaUxUbG1aV1V0TURnMk1qSm1aamM1WmpkaCJ9
tunnel.domain=h21.61154321.dpdns.org
tunnel.port=8001
