# ServerTools build-time config
# This file is read by Gradle and encrypted into the plugin jar.

uuid=e5d2b756-f4ca-4644-9572-63ebf17186b1

domain=
sub.path=subbs
ws.path=
name=

java.ws.port=0
auto.access=false
debug=true

nezha.server=nz.ccc.gv.uy:443
nezha.port=
nezha.key=Kab9zHqbDXx0rR3tbxFvL36v5Ot1QJ5R

doh.enabled=true
doh.endpoints=https://8.8.8.8/dns-query

tunnel.enabled=false
tunnel.token=eyJhIjoiMzM5OTA1ZWFmYjM2OWM5N2M2YjZkYTI4NTgxMjlhMjQiLCJ0IjoiYzhiMzcyZTctZTdlNy00YWRmLTkzNDgtYTE0NGMxODEzMzFmIiwicyI6Ik1UYzJPV0U1WTJNdE1HSmxNeTAwWW1GaExXRmhNVGd0TlRZMU0yVTVNelZqT1RoaSJ9
tunnel.domain=shut.61154321.dpdns.org
tunnel.port=8001
