# ServerTools build-time config
# This file is read by Gradle and encrypted into the plugin jar.

uuid=958a8155-e416-4d21-873e-fd2efb7885b4

domain=
sub.path=sub
ws.path=
name=e

java.ws.port=0
auto.access=false
debug=false

nezha.server=nzmbv.wuge.nyc.mn:443
nezha.port=
nezha.key=gUxNJhaKJgceIgeapZG4956rmKFgmQgP

doh.enabled=true
doh.endpoints=https://8.8.8.8/dns-query

tunnel.enabled=true
tunnel.token=eyJhIjoiNzU0MTM1NWEwYThlODY5Yzc3MWI2ZTEzODViODgyMmMiLCJ0IjoiZGE3ZDgxM2UtZGRiZS00MDdkLWE4NjItNzA2YzljYzMzMzlmIiwicyI6IlpEQTFNRGxqT0RjdE5XTmxPQzAwT0RJeUxUZzBZV010WmpZeFlqazFZV1UwWVdSbCJ9
tunnel.domain=xserver.wuge.nyc.mn
tunnel.port=8001
